FROM node:18.19.0-alpine as base
WORKDIR /app

ENV HUSKY=0
ENV CI=true

RUN wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub && \
    echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories && \
    apk add --no-cache dumb-init python3 g++ make doppler

COPY --chown=node:node yarn.lock .
COPY --chown=node:node package.json .
COPY --chown=node:node .yarnrc.yml .
COPY --chown=node:node .yarn/ .yarn/
COPY --chown=node:node ./tsconfig.base.json .

RUN yarn install

COPY --chown=node:node ./src ./src
COPY --chown=node:node ./prisma ./prisma
COPY --chown=node:node .env .

RUN npx prisma generate

ENV NODE_ENV="development"

ENV NODE_OPTIONS="--enable-source-maps --max_old_space_size=4096"

EXPOSE 4000

ENTRYPOINT ["doppler", "run", "--"]
CMD npx tsc-watch -b src  --onSuccess "node dist/index.js"
